spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/sbblogdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

settings:
  blog:
    title: Spring Boot Blog
